#!/bin/bash

# Create output file to store goto.py path output.
tmpfile="$(mktemp)"

# Pass temp file to goto.py so it can store the path to cd to 
# there. Any other output will just write to stdout.
goto.py --temp-file "${tmpfile}" "$@"

# Pull results from tmpfile and remove tmpfile.
path="$(cat "${tmpfile}")"
rm "${tmpfile}"

# Expand tilde in output.
path="${path/#\~/$HOME}"

# Go to directory if possible.
if [[ -d "${path}" ]] ; then 
    cd "${path}"
fi
